=== Irbiq/epam-java-web/XMLParsing/input/card.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.com/cards"
           xmlns="http://www.example.com/cards">

    <xs:element name="OldCards" type="OldCardsType"/>
    <xs:element name="Card" type="CardType" abstract="true"/>
    <xs:element name="OrdinaryCard" type="OrdinaryCardType"/>
    <xs:element name="GreetingCard" type="GreetingCardType"/>


    <xs:complexType name="OldCardsType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="OrdinaryCardType" name="OrdinaryCard"/>
            <xs:element type="GreetingCardType" name="GreetingCard"/>
            <xs:element type="CardType" name="Card" maxOccurs="unbounded" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="CardType">
        <xs:sequence>
            <xs:element type="xs:string" name="theme"/>
            <xs:element type="historyType" name="history"/>
            <xs:element name="valuable" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="thematic"/>
                        <xs:enumeration value="historical"/>
                        <xs:enumeration value="collection"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:nonNegativeInteger" name="id" use="required"/>
        <!--<xs:attribute type="xs:string" name="type" use="optional"/>-->
        <xs:attribute type="xs:string" name="sent" use="optional" default="false"/>
    </xs:complexType>


    <xs:complexType name="OrdinaryCardType">
        <xs:complexContent>
            <xs:extension base="CardType">

            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="GreetingCardType">
        <xs:complexContent>
            <xs:extension base="CardType">
                <xs:sequence>
                    <xs:element type="xs:string" name="text"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="historyType">
        <xs:sequence>
            <xs:element type="xs:string" name="country"/>
            <xs:element type="xs:nonNegativeInteger" name="year"/>
            <xs:element type="xs:string" name="author" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>


</xs:schema>

=== Irbiq/epam-java-web/XMLParsing/input/card.xml
<?xml version="1.0" encoding="UTF-8" ?>
<OldCards xmlns="http://www.example.com/cards" xsi:schemaLocation="http://www.example.com/cards card.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <!--You have a CHOICE of the next 3 items at this level-->
    <OrdinaryCard id="1" sent="false">
        <theme>Animal</theme>
        <history>
            <country>UA</country>
            <year>1992</year>
            <!--Optional:-->
            <author>Rooney</author>
        </history>
        <!--Optional:-->
        <valuable>thematic</valuable>
    </OrdinaryCard>

    <OrdinaryCard id="2" sent="false">
        <theme>Car</theme>
        <history>
            <country>USA</country>
            <year>1956</year>
            <!--Optional:-->
            <author>Messi</author>
        </history>
        <!--Optional:-->
        <valuable>thematic</valuable>
    </OrdinaryCard>

    <OrdinaryCard id="3" sent="true">
        <theme>Toy</theme>
        <history>
            <country>BY</country>
            <year>1992</year>
            <!--Optional:-->
            <author>Kasiski</author>
        </history>
        <!--Optional:-->
        <valuable>collection</valuable>
    </OrdinaryCard>

    <OrdinaryCard id="4" sent="false">
        <theme>Animal</theme>
        <history>
            <country>RU</country>
            <year>1999</year>
        </history>
    </OrdinaryCard>

    <OrdinaryCard id="5" sent="false">
        <theme>Football</theme>
        <history>
            <country>UA</country>
            <year>1992</year>
        </history>
        <!--Optional:-->
        <valuable>thematic</valuable>
    </OrdinaryCard>

    <OrdinaryCard id="6" sent="true">
        <theme>Animal</theme>
        <history>
            <country>UA</country>
            <year>1992</year>
        </history>
    </OrdinaryCard>


    <OrdinaryCard id="7" sent="true">
        <theme>Football</theme>
        <history>
            <country>UK</country>
            <year>1732</year>
        </history>
        <!--Optional:-->
        <valuable>collection</valuable>
    </OrdinaryCard>


    <OrdinaryCard id="8" sent="false">
        <theme>Building</theme>
        <history>
            <country>USA</country>
            <year>1892</year>
        </history>
        <!--Optional:-->
        <valuable>historical</valuable>
    </OrdinaryCard>


    <GreetingCard id="1" sent="false">
        <theme>Animal</theme>
        <history>
            <country>DE</country>
            <year>1645</year>
            <!--Optional:-->
            <author>Ronaldo</author>
        </history>
        <!--Optional:-->
        <valuable>historical</valuable>
        <text>Congrats</text>
    </GreetingCard>

    <GreetingCard id="2" sent="false">
        <theme>Car</theme>
        <history>
            <country>FR</country>
            <year>1973</year>
        </history>
        <text>Congrats</text>
    </GreetingCard>

    <GreetingCard id="3" sent="false">
        <theme>Football</theme>
        <history>
            <country>BY</country>
            <year>2000</year>
        </history>
        <!--Optional:-->
        <valuable>historical</valuable>
        <text>WE ARE THE CHAMPS</text>
    </GreetingCard>
    <GreetingCard id="4" sent="true">
        <theme>Fish</theme>
        <history>
            <country>UK</country>
            <year>2006</year>
            <!--Optional:-->
            <author>Smith</author>
        </history>
        <!--Optional:-->
        <valuable>historical</valuable>
        <text>Congrats</text>
    </GreetingCard>

    <GreetingCard id="5" sent="false">
        <theme>Football</theme>
        <history>
            <country>FR</country>
            <year>2009</year>
            <!--Optional:-->
            <author>Stan</author>
        </history>
        <!--Optional:-->
        <valuable>historical</valuable>
        <text>Congrats</text>
    </GreetingCard>
    <GreetingCard id="6" sent="true">
        <theme>Building</theme>
        <history>
            <country>CND</country>
            <year>2015</year>
            <!--Optional:-->
            <author>Thrump</author>
        </history>
        <!--Optional:-->
        <valuable>historical</valuable>
        <text>Congrats</text>
    </GreetingCard>
    <GreetingCard id="7" sent="true">
        <theme>Glory</theme>
        <history>
            <country>DNM</country>
            <year>2017</year>
            <!--Optional:-->
            <author>Lamar</author>
        </history>
        <!--Optional:-->
        <valuable>collection</valuable>
        <text>Congrats</text>
    </GreetingCard>
    <GreetingCard id="8" sent="false">
        <theme>Nature</theme>
        <history>
            <country>BLG</country>
            <year>2003</year>
        </history>
        <text>Congrats</text>
    </GreetingCard>

</OldCards>
